src-d/jgit-spark-connector

src/main/scala/tech/sourced/api/iterator/ReferenceIterator.scala
src/main/scala/tech/sourced/api/iterator/RepositoryIterator.scala
src/main/scala/tech/sourced/api/iterator/RootedRepoIterator.scala
src/main/scala/tech/sourced/api/util/GitUrlsParser.scala
src/test/scala/tech/sourced/api/BaseSivaSpec.scala
src/test/scala/tech/sourced/api/BaseSparkSpec.scala
src/test/scala/tech/sourced/api/iterator/BaseRootedRepoIterator.scala
src/test/scala/tech/sourced/api/iterator/ReferenceIteratorSpec.scala
src/test/scala/tech/sourced/api/iterator/RepositoryIteratorSpec.scala
src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala

Using a base abstract class RootedRepoIterator, we add two implementations, one of them to iterate repository metadata (repository id, urls, is fork) and references metadata (repository_id, name, hash).
With this RootedRepoIterator we should be able to implement CommitIterator and BlobIterator too.
Filter logic must be implemented before start with BlobIterator.
- Split test logic into Traits to be able to use them in all the Specs.
- Added a BaseRootedRepoIterator trait with a helper to test iterators more easly.

	RepositoryIterator and ReferenceIterator implementations

---

build.sbt
src/main/scala/tech/sourced/api/DefaultSource.scala
src/main/scala/tech/sourced/api/Implicits.scala
src/main/scala/tech/sourced/api/Schema.scala
src/main/scala/tech/sourced/api/iterator/CommitIterator.scala
src/main/scala/tech/sourced/api/provider/SivaRDDProvider.scala
src/test/scala/tech/sourced/api/DefaultSourceSpec.scala
src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala

This PR put all previous work together:
- We create a generic GitRelation that depending of the table name provided, it is created with a specific schema and a specific metadata iterator.
- Fix some typos on Schema
- Fix some typos on implicit methods
- Fix bug when a reference is not pointing to a commit
Blobs table is missing because is mandatory filtering to provide it.

First real implementation of GitRelation 

---

src/test/scala/tech/sourced/api/iterator/BaseRootedRepoIterator.scala

Filter by siva filename to get always the same siva file, because partitions are not always the same with the same content.

Get always the same siva file

---

src/main/scala/tech/sourced/api/DefaultSource.scala
src/main/scala/tech/sourced/api/Implicits.scala
src/main/scala/tech/sourced/api/Schema.scala
src/main/scala/tech/sourced/api/iterator/BlobIterator.scala
src/test/resources/log4j.properties
src/test/scala/tech/sourced/api/BaseSparkSpec.scala
src/test/scala/tech/sourced/api/DefaultSourceSpec.scala
src/test/scala/tech/sourced/api/iterator/BlobIteratorSpec.scala

In commit table, we have hashes of commits, which are used to get trees -> blobs.
Current implementation does not filter:
- repository (so same blob can happen in different repository)
- refs
It leverages `ColumnFilters` from #24 (need to be merged first) in order to get particular commit hashes, rather then iterating all refs HEADs.

BlobIterator implementation

---

.travis.yml
build.sbt
local-install-enry-java.sh
src/main/scala/tech/sourced/api/Implicits.scala
src/main/scala/tech/sourced/api/customudf/CustomUDF.scala
src/test/scala/tech/sourced/api/BaseSparkSpec.scala
src/test/scala/tech/sourced/api/customudf/CustomUDFSpec.scala

Currently is needed to have [enry-java](https://github.com/src-d/enry/tree/master/java) in your local ivi2 repo.

Added language detection

---

src/main/scala/tech/sourced/api/Implicits.scala
src/main/scala/tech/sourced/api/Schema.scala
src/main/scala/tech/sourced/api/SparkAPI.scala
src/main/scala/tech/sourced/api/package.scala
src/test/scala/tech/sourced/api/BaseSparkSpec.scala
src/test/scala/tech/sourced/api/DefaultSourceSpec.scala
src/test/scala/tech/sourced/api/customudf/CustomUDFSpec.scala

I think adding this function to the spark session simplifies a bit the experience of the user of the library.
Before
```scala
spark.sqlContext.setConf("tech.sourced.api.repositories.path", "/path/to/files")
```
Now
```scala
spark.setRepositoriesPath("/path/to/files")
```
We could even check if the path exists and contains siva files there and so on in the future.

implicits: make SparkAPI the entrypoint instead of using an implicit

---

src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala
src/test/resources/log4j.properties

Changes:
- adds synchronization around the repository copy
- adds logging to RepositoryProvider
Motivation:
#28 with atomic `Map.getOrElseUpdate` might be not enough, as it still can run file copy multiple times.
According to the [`MapLike.html#getOrElseUpdate`](https://www.scala-lang.org/api/current/scala/collection/mutable/MapLike.html#getOrElseUpdate(key:K,op:=>V):V)  docs:
> Concurrent map implementations may evaluate the expression op multiple times, or may evaluate op without inserting the result.

Fix: race condition on copy

---

.travis.yml
build.sbt

#41 introduced a netty version, fixed for gRPC and `./sbt assembly` require some guidance in such cases.
This PR fixes that and adds `./sbt assembly` to CI to avoid such things in the future

HOTFIX: fix building a fatJar

---

src/main/scala/tech/sourced/api/package.scala
src/test/scala/tech/sourced/api/DefaultSourceSpec.scala

Adds `getReference`,  `getHEAD` and `getMaster` for parity with python API.

api: add filters to reference dataframes for python api parity

---

src/main/scala/tech/sourced/api/SparkAPI.scala

Fixes #52 
Now it crashes with something like
```
py4j.protocol.Py4JJavaError: An error occurred while calling z:tech.sourced.api.SparkAPI.apply.
: org.apache.spark.SparkException: the given repositories path (/path/to/siva/files) does not exist, so siva files can't be read from there
at tech.sourced.api.SparkAPI.setRepositoriesPath(SparkAPI.scala:72)
at tech.sourced.api.SparkAPI$.apply(SparkAPI.scala:141)
at tech.sourced.api.SparkAPI.apply(SparkAPI.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```

api: throw error if the repositories path does not exist

---

src/main/scala/tech/sourced/api/DefaultSource.scala
src/main/scala/tech/sourced/api/iterator/CleanupIterator.scala
src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala
src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala

Fixes #29 
I implemented a `CleanupIterator`, which is basically an iterator extending `InterruptibleIterator` that executes some cleanup code when there is an exception (`Throwable` because `TaskKilledException` is not public :disappointed: )
Whenever a repository is fully iterated and done with (or something was thrown from inside), it's closed and its unpacked files deleted if there is nobody else using it. Otherwise, just keeps them open until the last one using them closes the repo.
I don't personally fancy much the refcount approach for this, but you still need it if you add a listener on the task context, because multiple tasks can be using the same repo. The iterator approach I felt it was cleaner than the task context one and `CompletionIterator` is private. Anyway, …

iterator: implement CleanupIterator to clean unpacked resources

---

src/main/scala/tech/sourced/api/package.scala

To be able to improve the Optimized LogicalPlan in the future, we should clean the execution tree as much as we can. We deleted distinct() method calls in places that are not needed.

Remove unnecessary calls to distinct() method

---

python/sourced/spark/api.py
python/test/test_api.py
src/main/scala/tech/sourced/api/Schema.scala
src/main/scala/tech/sourced/api/SparkAPI.scala
src/main/scala/tech/sourced/api/iterator/BlobIterator.scala
src/main/scala/tech/sourced/api/iterator/CommitIterator.scala
src/main/scala/tech/sourced/api/iterator/RootedRepoIterator.scala
src/main/scala/tech/sourced/api/package.scala
src/main/scala/tech/sourced/api/util/ColumnFilter.scala
src/test/scala/tech/sourced/api/DefaultSourceSpec.scala
src/test/scala/tech/sourced/api/iterator/BaseRootedRepoIterator.scala
src/test/scala/tech/sourced/api/iterator/BlobIteratorSpec.scala
src/test/scala/tech/sourced/api/iterator/CommitIteratorSpec.scala
src/test/scala/tech/sourced/api/util/ColumnFilterSpec.scala

Closes #68 
Closes #62 
BlobIterator now returns the files of each commit of each ref of each repo, instead of just the files on all ref head.
The schema of the files table is also changed to contain repository_id and reference_name so the filters are pushed down to the iterator and some optimizations can be done for the retrieval of just a small amount of files with certain restrictions such
as just retrieving files of a few hashes or references.
That said, this is just a temporary hack until more clever measures are put in place, because now we have two columns that will always be null and will always be dropped from the dataframe just for the sake of getting the filters pushed down.
SparkAPI has now a method `getFiles` to retrieve files given a set of repositories, references and/or …

return all commit files in BlobIterator, implement getFiles in api

---

.travis.yml
build.sbt
project/Dependencies.scala
project/plugins.sbt

Changing from jacoco to scoverage because:
- Jacoco sbt plugin is not working correctly if you want to execute test from Intellij IDE
- Scoverage plugin is more updated than Jacoco one
- Scoverage is the standard to measure coverage on codecov examples
Fixes https://github.com/src-d/spark-api/issues/40

Change jacoco to scoverage

---

.dockerignore
.travis.yml
Makefile
README.md

I followed the same structure bblfsh use to push the server images.
This PR hasn't been tested because it needs to be merged and tagged on master.
For the moment the image tag is built as `dev-[7 first digits from spark-api HEAD commit]-dirty`
Docker credentials are already set in travis.

Automated docker build and push task in Travis CI

---

.travis.yml
Makefile

Download the base image and install all the needed dependencies to build the docker image takes too long to run in every build.
Move the docker build command to deploy phase, to be executed only when a tag is created.

Only ejecute docker push on tag creations

---

src/main/scala/tech/sourced/api/SparkAPI.scala
src/main/scala/tech/sourced/api/package.scala

Also adds docs to `getFirstReferenceCommit`

docs: remove mentions about getFiles from DataFrame being slow

---

Dockerfile
Makefile
README.md

- Now the image and the Makefile make use of `bblfshd`
- There are new rules `make docker-bblfsh-install-drivers` and `make docker-bblfsh-list-drivers`to make easy `bblfshd` usage.
The current notebook example fails in the last commands because of selecting `repository_id` and `reference_name` columns. I assume this will be fixed in https://github.com/src-d/spark-api/issues/92.
The rest of modifications are tested in my local machine and seem to work well.

Use bblfshd and fix documentation

---

README.md

- Changed pip command to download sourced-spark-api from pypi
- Changed package name to point to the proper coordinates

fixed jitpack coordinates and pip install commands

---

_examples/README.md
_examples/notebooks/Basic+Example.ipynb
_examples/pyspark/pyspark-shell-basic.md
_examples/pyspark/pyspark-shell-classifying-languages.md
_examples/pyspark/pyspark-shell-lang-and-uast.md
_examples/pyspark/pyspark-shell-schemas.md
_examples/pyspark/pyspark-shell-uast-extraction.md
_examples/scala/spark-shell-basic.md
_examples/scala/spark-shell-classifying-languages.md
_examples/scala/spark-shell-lang-and-uast.md
_examples/scala/spark-shell-schemas.md
_examples/scala/spark-shell-uast-extraction.md

I just added a few basic examples for spark, pyspark, and jupyter. I was trying to use `classifyLanguage` and `extractUASTs`functionality but they don't work right now, so I didn't add any example about. I'll try to make it work somehow since https://github.com/src-d/spark-api/pull/57 doesn't work for me.
It would be nice if you could suggest other kind of examples to include, based on some usage  cases.

[DOC] added basic examples to works with docsrv

---

project/Dependencies.scala

- `client-scala` dependency now points to maven central
- `enry-java` version updated to `1.5.1`

Updated client-scala and enry dependencies

---

_examples/notebooks/Basic+Example.ipynb
examples/notebooks/Basic+Example.ipynb

- Added the following example to the notebook:
`head_files.where('lang = "Python"').extract_uasts().select('file_hash', 'path', 'lang', 'uast').limit(10).show()`
```
+--------------------+--------------------+------+--------------------+
|           file_hash|                path|  lang|                uast|
+--------------------+--------------------+------+--------------------+
|22df25a3d87c3147e...|       dec_to_hex.py|Python|[0A 06 4D 6F 64 7...|
|859b78bb87c0f7f67...|youtube-downloade...|Python|[0A 06 4D 6F 64 7...|
|ff4fa0794274a7ffb...|fibonacci/fibonac...|Python|[0A 06 4D 6F 64 7...|
|73af2324d76e5e9c1...|powerdown_startup.py|Python|[0A 06 4D 6F 64 7...|
|5b313b2ae75e522e1...| password_cracker.py|Python|[0A 06 4D 6F 64 7...|
|522143e341780459b...|sqlite_table_chec...|Python|[0A 06 …
```

UAST extraction example in notebook

---

src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala
src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala

It's missing HDFS tests, but this is intended to be an optimization for the local usecase, so we should merge this and release it for the infrastructure team to update the notebooks and validate how much faster it is.
Then I will setup the minicluster for unit testing and test against HDFS, which should work, anyway.

provider: do not copy already local siva files

---

project/Dependencies.scala

New scala client version includes synchronization when installing the jar shared object to local filesystem, which before could lead to weird stuff

sbt: upgrade client-scala version

---

build.sbt
project/Dependencies.scala

Since `siva-java` is now available on `maven central`, the dependency can be obtained from there instead from `jitpack`.

Download siva-java dependency from maven central

---

README.md

Clarify a bit windows support to specify that there is no windows support in neither enry-java nor client-scala

Clarify windows support

---

src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/Engine.scala

***This PR is related to https://github.com/src-d/engine/issues/132***
- I tested the changes and I could see how the siva-files aren't remove when the skipCleanup option is set to true while they were always removed before regardless the option were set or not.
***What was happening***
The `skinCleanup` K-V configuration was being set in the [SparkConf](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.SparkConf) object which is the configuration for the [SparkContext](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.SparkContext). It is in charge to manage the cluster's configuration stuffs. The `SparkConf` is given and cloned to the `SparkContext` when it is instantiated, so after that the `SparkConf` can't be used to add and remove …

Fixed skipCleanup option

---

README.md

Add a Maven central badge to the README to easily let the user viewing the repo which is the latest version published on maven central.
**Example:**
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/tech.sourced/engine/badge.svg)](https://maven-badges.herokuapp.com/maven-central/tech.sourced/engine)

add maven central badge to README

---

src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/Engine.scala
src/main/scala/tech/sourced/engine/GitOptimizer.scala

The main reason for this PR comes from #144.
Changes:
- Replaced `SQLContext`by `SparkSession` objects where possible.
- Use of `SparkSession.conf`instead of `SQLContext.getConf` to handle the K-V configuration store.
- I guessed that `Provider` classes are providing `RDD` to be able to use just with `spark.core` without `spark.sql`, so they still are using `SparkContext`

Normalize spark configuration and SparkSession/SQLContext/SparkContext usage

---

src/main/scala/tech/sourced/engine/package.scala

This PR removes `val localPathKey`
```scala
/** Local spark directory. */
private[engine] val localPathKey = "spark.local.dir"
```
This is private to the engine package, but it is not used anywhere, so it could be removed.
On the other hand, we have the wrapper:
```scala
object UtilsWrapper {
def getLocalDir(conf: SparkConf): String = Utils.getLocalDir(conf)
}
```
Which returns the current value for the local dir configuration.
About local dir configuration it can be set in different ways and this function explicits the preferenced order spark uses (from the `Utils.getLocalDir`'s scaladoc):
```scala
/**
* Get the path of a temporary directory.  Spark's local directories can be configured through
* multiple settings, which are used with the following precedence:
*
*   - If called from …
```

Removed val localPathKey

---

.travis.yml
README.md
python/Makefile

This PR simplifies the python testing task, at least in local.
Changes:
- `python/Makefile` does the copy of the fatjar before run python test
- python test are running now just with `cd python; make test`
- changed the `.travis.yml` to use the `make test` rule
- changed the `README` to reflect the changes

Modified python/Makefile to simplify testing task

---

README.md

Use of `wget url -O output-filename` flag should avoid name issues when the spark tgz is downloaded from a mirror using `wget`.
Related to https://github.com/src-d/engine/issues/157.

Modified README to use "-O" flag when wget is used.

---

build.sbt
project/Dependencies.scala
src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala
src/test/scala/tech/sourced/engine/provider/RepositoryProviderSpec.scala

This change manage to process ~1200 siva files repositories in less time:
Executed code: 
```scala
spark.time(engine.getRepositories.getReferences.count())
```
Using one core:
- Before: ~5 min
- Now: ~4,5 min
Using 8 cores:
- Before: ~4 min
- Now: ~2 min

Use an object pool to mange Repositories instances

---

src/main/scala/tech/sourced/engine/util/Bblfsh.scala

Closes #168 
Current implementation creates one client per call. In cases where the
connections are closed at an slower pace than they are created it can
reach user limits and give errors.
This change creates a new client object the first time it is called and
returns it in the next calls.

Reuse bblfsh client instead of creating one per call

---

src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala
src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala

***This PR is related to #177***
The changes avoid to return an object to the pool which was already returned.
I don't know why, but when the DF is persisted to disk, the last repo in the RDD generated by the `BaseRelation.buildScan` is closed twice. Because of this, the NPE was thrown.
@ajnavarro @erizocosmico @jfontan do you know what is causing this behavior?

Fix NPE when persist DF to disk

---

README.md
python/sourced/engine/engine.py

Closes #160 
Closes #162 
As flaky as this might seem, there is nothing in the Py4J API to check if something imported does actually exist or not and all it throws is a `TypeError` so that's our best guess.

better error message when engine is missing from pyspark

---

README.md

Prerequisites is now a list with links to the projects. In quick start guide the instructions to download and run spark-shell are left in README as I have not found a quick guide to do that in the documentation.

Link to external doc instead of repeating instructions

---

src/test/scala/tech/sourced/engine/BaseSparkSpec.scala
src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala
src/test/scala/tech/sourced/engine/StorageLevelSpec.scala

Since persist is bound to a `SparkContext` and we reuse the same `SparkSession` for all the tests in `DefaultSourceSpec`, the storage level test has been located in a new class that use a different `SparkSession` to avoid erros in other tests that are not related.

Moved storage level test to a new class

---

README.md

docs: list scala 2.11.x as pre-requisite

---

build.sbt
project/Dependencies.scala

Fixes #210 
- Not include scala in fatjar
- Mark scala as provided
- Rewrite output `pom.xml` to remove all dependencies without `provided` scope and add the scala library as provided (since sbt or something else in the process adds it as compile even if you explicitly put it).
**NOTE:** this only works for maven repositories. That is, if you use `publishLocal`, it will not work, you need to use `publishM2` and use the local maven repository. Since we deploy on maven it should not matter much.

build: not include not provided deps on pom.xml, scala as provided

---

src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/Engine.scala
src/main/scala/tech/sourced/engine/GitOptimizer.scala

Before this PR, the `source` assignation as metadata to `AttributeReference` was done in the `SquashGitRelationJoin` so a code like this didn't work properly:
```scala
val repoDf = engine.getRepositories
repoDf.where("id='github.com/xiyou-linuxer/faq-xiyoulinux'").show
```
It was filtered by spark instead of us because the `source` it wasn't  set.
Now there is a new rule `AddSourceToAttributes` ensuring the `source` is set always.

Added rule to attach source to attributes

---

python/setup.py
python/sourced/__init__.py

Since we have two python packages in one namespace (`ml` and `engine` in `sourced`) it is good to use package namespace to make them work together.
You can find more info about package namespaces [here](http://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages).
One can check that everything works using pure ubuntu (for example using docker `docker run -it ubuntu bash`) and run:
``` bash
apt-get update
apt-get install -y --no-install-suggests --no-install-recommends ca-certificates locales git python3 python3-dev libxml2 libxml2-dev libonig2 make gcc curl
curl https://bootstrap.pypa.io/get-pip.py | python3
mkdir workdir
cd workdir/
git clone https://github.com/zurk/ast2vec.git -b pack_namespace
git clone https://github.com/zurk/engine.git -b feature/pack_namespace
cd …
```

Add python package namespace

---

src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala

Now the output when a repository is getted or closed is showing the total amount of elements on the pool

Improve repository pool logs

---

README.md

Added explanation about how and why set `LANG` environment variable to avoid encoding issues.
it comes from #244

Document file name encoding issue

---

python/sourced/engine/engine.py

Fix https://github.com/src-d/engine/issues/268

Fix to "AttributeError: 'TypeError' object has no attribute 'message'" when handling unavailable engine.jar

---

src/main/scala/tech/sourced/engine/rule/SquashGitRelationsJoin.scala
src/main/scala/tech/sourced/engine/rule/SquashMetadataRelationsJoin.scala
src/test/scala/tech/sourced/engine/BaseSourceSpec.scala

We cannot optimize any kind of query to push down them to the GitDatasource.
Because of that, some of the queries appears to be freezed due a lack of an optimized output.
To avoid that, now we throw an error if the query cannot be optimized to fetch repositories metadata.

[Optimizer] Throw an error if the query cannot be optimized

---

src/main/scala/tech/sourced/engine/rule/SquashGitRelationsJoin.scala
src/test/scala/tech/sourced/engine/FilterUDFSpec.scala

Spark optimizes equality filters removing them and relaying on the `Scan GitRelation` to apply the filter as you can see in #277. Since our `UDF`s are generating data, the data to filter is not in the data source, so we must generate again the Filter node that spark is removing.
Now the `Physical Plan` generated is:
```scala
val langDf = engine
.getRepositories
.getReferences
.getCommits
.getBlobs
.classifyLanguages
val filteredLang = langDf.select("repository_id", "path", "lang").where("lang='Python'")
filteredLang.explain(true)
```
Output:
```
== Physical Plan ==
*Project [repository_id#60, path#49, UDF(is_binary#63, path#49, content#62) AS lang#280]
+- *Filter (UDF(is_binary#63, path#49, content#62) = Python)
+- *Scan GitRelation(org.apache.spark.sql.SparkSession@3b446d7,StructType(Stru …
```

Fixed language filtering

---

python/sourced/engine/engine.py

Fixes the `head_ref` and `master_ref` Python API methods using the Scala methods instead of redoing the logic again in Python.

fix head_ref and master_ref methods in Python API

---

_examples/pyspark/pyspark-shell-schemas.md
_examples/scala/spark-shell-schemas.md
src/main/scala/tech/sourced/engine/Engine.scala
src/main/scala/tech/sourced/engine/Schema.scala
src/main/scala/tech/sourced/engine/iterator/ReferenceIterator.scala
src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala
src/test/scala/tech/sourced/engine/iterator/BaseChainableIterator.scala

Adds `is_remote` column to `references` table so an user can identify if a reference was remote or not even after the rewrite from `refs/remotes/$REMOTE_NAME/$BRANCH` to `refs/heads/$BRANCH`.

add is_remote column to references table

---

src/test/scala/tech/sourced/engine/FilterUDFSpec.scala

10s vs 1m19s
since all we need to check is that filter works, no need to not filter by first ref commit, which is faster.
It's not a very critical improvement but as we keep adding tests these little things count in how much our test suite takes to run

make FilterUDFSpec faster filtering by only first ref commit

---

src/main/scala/tech/sourced/engine/rule/RelationOptimizer.scala
src/main/scala/tech/sourced/engine/rule/SquashGitRelationsJoin.scala

This adds a check that could not be performed before because not all `AttributeReference`s had a source. Now that they have it should be done to avoid marking as redundant filters that are not if the name of a field is used in more than one table, such as `hash` that's both in `references` and `commits`. It's not a very important thing, but better take care of it now than forget about it.

check sources when testing whether a join condition is reundant as filter

---

project/Dependencies.scala

(CI might fail as the version is still not available in maven)

upgrade siva-java so it handles files bigger than 2GB

---

src/main/scala/tech/sourced/engine/rule/SquashGitRelationsJoin.scala
src/test/scala/tech/sourced/engine/BaseSourceSpec.scala
src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala

Closes #267 
Closes #293 
Example output:
```
18/01/15 15:34:43 ERROR GitOptimizer: ********************************************************************************
18/01/15 15:34:43 ERROR GitOptimizer: * This Join could not be optimized. This might severely impact the performance *
18/01/15 15:34:43 ERROR GitOptimizer: * of your query. This happened because there is an unexpected node between the *
18/01/15 15:34:43 ERROR GitOptimizer: * two relations of a Join, such as Limit or another kind of unknown relation.  *
18/01/15 15:34:43 ERROR GitOptimizer: * Note that this will not stop your query or make it fail, only make it slow.  *
18/01/15 15:34:43 ERROR GitOptimizer: ********************************************************************************
18/01/15 15:34:43 ERROR GitOptimizer: * …
```

do not throw exception if join cannot be optimized, log warning

---

build.sbt
project/Dependencies.scala
src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/Engine.scala
src/main/scala/tech/sourced/engine/package.scala
src/main/scala/tech/sourced/engine/udf/ClassifyLanguagesUDF.scala
src/main/scala/tech/sourced/engine/udf/ConcatArrayUDF.scala
src/main/scala/tech/sourced/engine/udf/CustomUDF.scala
src/main/scala/tech/sourced/engine/udf/ExtractTokensUDF.scala
src/main/scala/tech/sourced/engine/udf/ExtractUASTsUDF.scala
src/main/scala/tech/sourced/engine/udf/QueryXPathUDF.scala
src/test/scala/tech/sourced/engine/udf/CustomUDFSpec.scala

First step to add Spark custom metrics from engine parts using spark-metrics project.
Addded timers on all critical UDFs and on repository provider.
UDF structure has been slightly refactored to avoid duplicated and unnecesary code.

Add metrics to Engine

---

src/main/scala/tech/sourced/engine/Engine.scala

I think is valuable to have the `session` member publicly available since it allows you to pass an `Engine` object throw your code containing all you need from `spark`.
For example, when engine is used by a third app you could want import `spark.sqlContext.implicits._` in some parts of your code. Having the session member available you don't need to pass the spark session and engine to those parts, just engine and use `import engine.session.sqlContext.implicits._`

Make Engine's session member public

---

README.md
_examples/README.md
_examples/notebooks/Example.ipynb
_examples/pyspark/pyspark-shell-schemas.md
_examples/scala/spark-shell-schemas.md
examples/notebooks/Example.ipynb
python/sourced/engine/engine.py
python/sourced/examples/repo_files.py
python/sourced/examples/uasts.py
python/test/test_engine.py
scalastyle-config.xml
src/main/scala/tech/sourced/engine/Engine.scala
src/main/scala/tech/sourced/engine/MetadataSource.scala
src/main/scala/tech/sourced/engine/QueryBuilder.scala
src/main/scala/tech/sourced/engine/Sources.scala
src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala
src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala
src/main/scala/tech/sourced/engine/iterator/ReferenceIterator.scala
src/main/scala/tech/sourced/engine/iterator/RepositoryIterator.scala
src/main/scala/tech/sourced/engine/package.scala
src/main/scala/tech/sourced/engine/util/Filters.scala
src/test/scala/tech/sourced/engine/BaseSourceSpec.scala
src/test/scala/tech/sourced/engine/EngineSpec.scala
src/test/scala/tech/sourced/engine/FilterUDFSpec.scala
src/test/scala/tech/sourced/engine/QueryBuilderSpec.scala
src/test/scala/tech/sourced/engine/iterator/BlobIteratorSpec.scala
src/test/scala/tech/sourced/engine/iterator/CommitIteratorSpec.scala
src/test/scala/tech/sourced/engine/iterator/GitTreeEntryIteratorSpec.scala
src/test/scala/tech/sourced/engine/util/FilterSpec.scala

This implements the ENIP-004, which makes the default behavior returning only
the last commit in a reference unless specifically asked to retrieve them all.
It has sort of a hack for making it work with the metadata source, since it
does not make use of the CommitIterator, which has a less hacky implementation.
Also, there's a complete rewrite of the filters and how they are used in the
iterators to allow more operators than just equality. As a side effect, 'OR'
operator is no longer supported. It was supported before, but only because it
was converted to an AND (and thus being a bug).
Fixes #303.
Closes #290.
This contains breaking changes and should be release in version 0.4.x! Be careful when merging this.

get only the last commit of a reference by default

---

.dockerignore
Dockerfile
Makefile

Fixes #318 
Advantages:
- No environment required to build the image
Downsides:
- Takes a lot more to build
- Adds a lot more files to the docker context (we need to build the jar inside, can't put them in the `.dockerignore`)

replace makefile build with docker multi-stage build

---

src/main/scala/tech/sourced/engine/package.scala
src/main/scala/tech/sourced/engine/udf/ClassifyLanguagesUDF.scala

Fixes #314 
Because of Spark optimizations, costly UDFs (and all UDFs, actually) may be invoked more than once. When the UDF is a substring or something like that, it's ok, but when your UDF computes the UAST of a blob or guesses its language, the thing becomes a little more delicate. Over a huge dataset, this could mean extracting the UAST and the language up to tens of times for each single blob! Which not only makes everything slow but sends a lot more jobs to babelfish.
To avoid this, we came up with this solution, use a `map` and transform the `Row`. That way, since it's not an UDF, it does not get done more than once. We still keep the UDFs just in case someone wants to execute them in a SQL query, though they would incur in the aforementioned issues, but that's ok.
Of course, this …

replace classifyLanguages and extractUASTs UDFs with maps

---

src/main/scala/tech/sourced/engine/provider/RepositoryRDDProvider.scala
src/test/scala/tech/sourced/engine/provider/RepositoryRDDProviderSpec.scala

Fixes #316 
Closes #235 
This allows bucketization of raw repositories and limits the files of the `siva` repo format to `*.siva` files.

allow bucketized raw repositories, limit siva files

---

src/main/scala/tech/sourced/engine/DefaultSource.scala
src/main/scala/tech/sourced/engine/MetadataSource.scala
src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala
src/test/scala/tech/sourced/engine/iterator/BaseChainableIterator.scala
src/test/scala/tech/sourced/engine/iterator/RepositoryIteratorSpec.scala
src/test/scala/tech/sourced/engine/provider/RepositoryProviderSpec.scala

The limit is set to the double of the number of parallelism. Without thischange there could be OutOfMemory problems when processing big repos.
Fixes #319

Limit the number of repositories kept in the pool

---

src/main/scala/tech/sourced/engine/util/Filters.scala

This PR follows the advice in [SI-4278](https://issues.scala-lang.org/browse/SI-4278) and makes filters serializable, thus avoids cluster-mode runtime exceptions like https://github.com/src-d/engine/issues/339
Please, feel free to provide a feedback if there is a better way of doing it.

Add default constructors to all Filters

---

src/main/scala/tech/sourced/engine/provider/ReadOnlyFileRepository.scala
src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala

Jgit's `FileRepository` checks 3 configuration files'
last modification date on every `getConfig`. This leads
to a big performance hit on some operations.
This commit adds a ReadOnlyFileRepository for optimizations
when the underlying repository is not expected to change.
It is now used for temporary repositories created out of siva
files.

add jgit ReadOnlyFileRepository implementation.

---

src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala

Fix #336.
A `RevWalkException` is thrown by `org.eclipse.jgit.revwalk.RevWalk.iterator` outside of the try/catch added in #347.

Catch RevWalkException in RefWithCommitIterator.hasNext

---

src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala

Implements #354.
The logs for errors that are ignored now have `debug` level. There are still some logs left as warnings because they look relevant to me, i.e. in MetadataIterator the messages about failing DB connections are still reported as warnings.

Change ignored errors log level to debug

---

src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala
src/main/scala/tech/sourced/engine/iterator/ChainableIterator.scala
src/main/scala/tech/sourced/engine/iterator/CleanupIterator.scala
src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala
src/main/scala/tech/sourced/engine/iterator/ReferenceIterator.scala
src/main/scala/tech/sourced/engine/iterator/RepositoryException.scala
src/main/scala/tech/sourced/engine/iterator/RepositoryIterator.scala

This PR is a proposal to add extra information when an untreated exception is caught in `CleanupIterator`.
The idea is that iterators can extend a new `CrashReporter` trait, and the global try/catch in `CleanupIterator` will check if the current iterator can add details to the exception.
Note: Each iterator will probably have extra useful debug details (maybe in `currentRow`?) that can be added later. I wanted to make this PR as simple as possible to request feedback.
Now the exceptions will look like this:
```
scala> engine.getRepositories.getReferences.getCommits.count()
[Stage 0:>                                                          (0 + 3) / 3]18/04/06 20:24:08 ERROR Executor: Exception in task 2.0 in stage 0.0 (TID 2)
java.lang.Exception: RefWithCommitIterator crashed for …
```

Add detailed debug info when an iterator crashes

---

src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala

iterator: traverse all commits when iterator is not chained

---

python/requirements.txt
python/setup.py

python: require 2.2.x pyspark instead of >= 2.0.0

---

build.sbt

To avoid problems with other shaded packages from transitive dependencies, added a unique key to shade our packages.

Change shaded package name for protobuf

---

python/requirements.txt
python/setup.py

Since I got no responses, did PR to solve [this issue](https://github.com/src-d/engine/issues/390).
**TL;DR:** The `pyspark` version we use is marked as `2.2.0` once installed, but `2.2.0.post0` in PyPi, which leads to reinstalling `pyspark` at each upgrade/install of the engine, even if the correct spark is already present. This will remove that behavior.

Update PySpark version

---

python/test/test_engine.py
src/test/scala/tech/sourced/engine/udf/CustomUDFSpec.scala

Bblfsh python driver version 2.0.0 changes the order of nodes on his output. To make tests pass, we need to check the content of the output but not the order.

Fix tests to make them work with new bblfsh driver version

---

.travis.yml
Makefile
README.md
project/Dependencies.scala
python/setup.py
src/main/scala/tech/sourced/engine/compat/compat.scala
src/main/scala/tech/sourced/engine/rule/AddSourceToAttributes.scala
src/main/scala/tech/sourced/engine/rule/SquashGitRelationsJoin.scala
src/main/scala/tech/sourced/engine/rule/SquashMetadataRelationsJoin.scala

- A new private package `compat` is added with compatibility shims.
- Shims for apply/unapply on LogicalRelation are added with compatibility
with Spark 2.2.x and 2.3.x.
- If an unsupported Spark version is used, a human-readable exception is thrown.

add support for Apache Spark 2.3

---

src/main/scala/tech/sourced/engine/udf/CustomUDF.scala

Noticed this while reading through your code.

Log line cleanup: `SparMetric` to `SparkMetric`
