.gitignore, build.sbt, project/Dependencies.scala, project/build.properties, src/main/scala/tech/sourced/api/DefaultSource.scala, src/main/scala/tech/sourced/api/Implicits.scala, src/main/scala/tech/sourced/api/Schema.scala, src/test/scala/tech/sourced/api/DefaultSourceSpec.scala
To be able to start planning a concrete API, we can use this datasource as an example.
=> Add Mocked datasource

.gitignore, sbt
Adding convenience sbt wrapper.
=> Add sbt build wrapper

src/main/scala/tech/sourced/api/util/ColumnFilter.scala, src/test/scala/tech/sourced/api/util/ColumnFilterSpec.scala
ColumnFilter object that is able to:
- Return true or false to check if we need to filter a specific row from the iteration
- Get a list of matching elements to be able to filter directly using them
=> ColumnFilter helper to use into iterator

build.sbt, project/assembly.sbt
- With this plugin we can generate a fatjar suitable to be sent to a Spark cluster.
=> Add assembly plugin

Dockerfile, build.sbt, examples/Basic+Example.ipynb
All notebooks inside examples folder will be included on the image.
To run the container, the preliminary command is: docker run -p 8888:8888 -v /path/to/my/root-repositories:/repositories [CONTAINER_NAME]
=> Add preliminary Dockerfile

README.md
This PR is related to https://github.com/src-d/spark-api/issues/34.
A first approach to a explanation on how to install and run spark-api, pyspark examples should be added too. Feedback is welcome!
=> [DOC] Installation and How to Run spark-api in README

README.md
Few high-level details on current architecture of Spark API
=> Doc: update high-level description in README

src/main/scala/tech/sourced/api/DefaultSource.scala, src/main/scala/tech/sourced/api/SparkAPI.scala, src/main/scala/tech/sourced/api/package.scala, src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala, src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala
Adds a configurable option to skip cleanup of unpacked resources and siva files (even though unpacked resources are not cleaned yet)
=> provider: configurable option to skip cleanup of unpacked resources

README.md
Quick doc update, missing from https://github.com/src-d/spark-api/pull/43#discussion_r139947920
=> Doc: quick README update

src/main/scala/tech/sourced/api/DefaultSource.scala, src/main/scala/tech/sourced/api/Schema.scala, src/main/scala/tech/sourced/api/iterator/BlobIterator.scala, src/main/scala/tech/sourced/api/iterator/CleanupIterator.scala, src/main/scala/tech/sourced/api/iterator/CommitIterator.scala, src/main/scala/tech/sourced/api/iterator/ReferenceIterator.scala, src/main/scala/tech/sourced/api/iterator/RepositoryIterator.scala, src/main/scala/tech/sourced/api/iterator/RootedRepoIterator.scala, src/main/scala/tech/sourced/api/package.scala, src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala, src/main/scala/tech/sourced/api/provider/SivaRDDProvider.scala, src/main/scala/tech/sourced/api/udf/ClassifyLanguagesUDF.scala, src/main/scala/tech/sourced/api/udf/CustomUDF.scala, src/main/scala/tech/sourced/api/udf/ExtractUASTsUDF.scala, src/main/scala/tech/sourced/api/util/ColumnFilter.scala, src/main/scala/tech/sourced/api/util/MD5Gen.scala
=> docs: add ScalaDoc to everything

.travis.yml
=> Revert "Deploy docker artifact and python dependency"

python/sourced/examples/repo_files.py, python/sourced/spark/api.py, python/test/test_api.py
Fixes #93 
Maybe we should add a few examples in the python notebook using this?
=> python: implement first_reference_commit

project/assembly.sbt, project/depTree.sbt, project/plugins.sbt
- All plugins have been placed in `project/plugins.sbt`
=> plugins gathered in project/plugins.sbt

Dockerfile
Doing this, we are going to have a good feedback about the progress of the actual job.
The plugin: https://github.com/mozilla/jupyter-spark
Some images:
=> Install jupyter-spark plugin on container

src/main/scala/org/apache/spark/UtilsWrapper.scala, src/main/scala/tech/sourced/api/DefaultSource.scala, src/main/scala/tech/sourced/api/provider/RepositoryProvider.scala, src/test/scala/tech/sourced/api/iterator/BaseRootedRepoIterator.scala, src/test/scala/tech/sourced/api/provider/RepositoryProviderSpec.scala
To be able to get the spark local dir correctly (from a spark conf, spark defaults file, environment variable) we should use a special Utils method to do this.
=> Get local dir correctly

README.md
=> update badges to src-d/engine

Dockerfile
Image is large enough yet, let's avoid not necessary layers.
=> Avoid creating a layer per RUN command

.dockerignore, .travis.yml, Dockerfile, project/Dependencies.scala
Closes #134 
Fixes a memory leak when calling `Libuast.filter`
=> upgrade client-scala to version 1.3.3

README.md, _examples/pyspark/pyspark-shell-basic.md, _examples/pyspark/pyspark-shell-classifying-languages.md, _examples/pyspark/pyspark-shell-lang-and-uast.md, _examples/pyspark/pyspark-shell-schemas.md, _examples/pyspark/pyspark-shell-uast-extraction.md, _examples/pyspark/pyspark-shell-xpath-query.md, _examples/scala/spark-shell-basic.md, _examples/scala/spark-shell-classifying-languages.md, _examples/scala/spark-shell-lang-and-uast.md, _examples/scala/spark-shell-schemas.md, _examples/scala/spark-shell-uast-extraction.md, _examples/scala/spark-shell-xpath-query.md
- Updated README to point to maven central when use engine as a dependency
- Changed examples to use engine dependency from maven central
=> Updated documentation to download engine from maven central

src/main/scala/tech/sourced/engine/util/MD5Gen.scala
The instance takes 2ms to be created and MessageDigest is not thread safe.
=> Create a new MessageDigest instance per call

_examples/pyspark/pyspark-shell-lang-and-uast.md
A new line was missed in python code.
=> [documentation] Fix missed new line

documentation/proposals/README.md
Link is case sensiteve :dagger:
=> Fix Typo in link

python/sourced/engine/engine.py, src/main/scala/tech/sourced/engine/package.scala
=> docs: suggest usage of first reference commit in commits methods

python/sourced/engine/engine.py
* Sorted alphabetically
* Less code
* Preserves the original signature using functools.wraps()
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>
=> Refactor SourcedDataFrame's method wrappers

python/test/test_engine.py, src/main/scala/tech/sourced/engine/package.scala, src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala
=> engine: make getFiles with a refs dataframe get only first commit

README.md, build.sbt
Closes #210 
Fiiiiiinaaaaaally fixed.
=> Publish artifact with "slim" classifier for application usage

src/main/scala/tech/sourced/engine/Engine.scala
=> Removed existence checking of directory resources

src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala, src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala, src/main/scala/tech/sourced/engine/iterator/ReferenceIterator.scala, src/main/scala/tech/sourced/engine/iterator/RepositoryIterator.scala, src/main/scala/tech/sourced/engine/iterator/RootedRepoIterator.scala, src/main/scala/tech/sourced/engine/iterator/TreeEntryIterator.scala
Change Map[String, ()=> Any] to Map[String, Any]
=> Simplify the iterators map structure

examples/notebooks/Example.ipynb
=> Update file_hash column to blob_id on notebook examples.

src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala
Remove map that can contains potentially all the blobs on all the repositories on the dataset. It causes a OOM.
=> Fix OOM on BlobIterator

project/Dependencies.scala
It should fix https://github.com/src-d/engine/issues/271
=> fix old `enry`

src/test/resources/log4j.properties
=> Mute loggers on tests

python/sourced/engine/engine.py, python/test/test_engine.py
=> Added Python bindings for metadata sources

README.md, src/main/scala/tech/sourced/engine/iterator/RootedRepo.scala, src/main/scala/tech/sourced/engine/package.scala, src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala, src/test/scala/tech/sourced/engine/util/RepoUtils.scala
=> engine: make getHEAD match also HEAD, rewrite remote refs

project/Dependencies.scala
=> upgrade siva-java

CODE_OF_CONDUCT.md, README.md
@campoy should we put anything else in the README regarding the CoC or is it okay with just the link to the md?
=> add code of conduct and add it to README

src/main/scala/tech/sourced/engine/udf/ClassifyLanguagesUDF.scala
That's the most we can do at the UDF level for the data we have, print a log with the failure and the filename. And only considering this throws an exception, if it simply makes everything die or it does not this is for nothing.
=> better reporting of enry exceptions

project/Dependencies.scala
Signed-off-by: Alfredo Beaumont <alfredo.beaumont@gmail.com>
=> dependencies: Bump enry-java to 1.6.3

documentation/proposals/ENIP-004.md
=> add proposal for making getFirstReferenceCommit default behavior

.travis.yml
Signed-off-by: Miguel Molina <miguel@erizocosmi.co>
=> make build before releasing

examples/notebooks/Example.ipynb, src/main/scala/tech/sourced/engine/iterator/ReferenceIterator.scala, src/main/scala/tech/sourced/engine/iterator/RootedRepo.scala
Adding some more examples and adding sampling and limits to give users faster results the first time they run it. I also added  some more printSchema() statements so that the first time user unknown to Spark can get an understanding on how it works. It also now passes on the param to read from raw repositories, which is the more common behaviour for most users.
This is notebook IMO still has too few examples and I'd like to encourage everyone to add more interesting ones.
=> Modified the example notebook

python/MANIFEST.in
=> include version.txt file for versions in pypi

src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
=> avoid exceptions being thrown because of MissingObjectExceptions

src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala
=> Return a warning instead of an error on missing subtree

Dockerfile
This PR fix https://github.com/src-d/engine/issues/337 issue, all described there.
=> Fix #337 issue

README.md, project/Dependencies.scala
Change readme to don't say that engine is compatible with other versions than 2.2.x
=> Update version to 2.2.1 and fix readme

src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala
Fixes #336 
This is the cleanest way I found to solve this bug. What it does, basically, is preloading the next result in the `hasNext`. That way, if there's a problem doing so, we just skip it and call `hasNext` again to continue as if nothing happened. `hasNext` is now tail recursive, so the stack won't blow up.
Other solutions I could think of:
- Transform the iterator to return `Option[ReferenceWithCommit]` (which is a PITA for the user of this iterator).
- Make the client responsible for catching the error (which is an even bigger PITA)
- Retry N times (which is @smola's quick fix that's posted on the issue), but if this fails all the N times, an exception is thrown, which leaves us with the same problem, just a different type of exception.
=> iterator: skip RevWalkExceptions in RefWithCommitIterator

Dockerfile
=> Install git on openjdk docker container

Dockerfile
=> dockerfile: set lang in env variable

.travis.yml
=> ci: upload images in master as well

src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala
Fixes #357.
The code makes `BlobIterator.readFile` return `emptyByteArray` in case of a `MissingObjectException`. `mapColumns` is already storing empty byte arrays for binary Blobs.
=> Add catch for MissingObjectException in BlobIterator

Makefile
=> makefile: do not build image when its not going to be pushed

src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala
=> Fix MissingObjectException on tree iterator

.travis.yml, README.md, python/Makefile, python/requirements.txt, python/sourced/engine/__init__.py, python/sourced/engine/engine.py, python/test/test_engine.py
Fixes #352 
**NOTE:** that this package will need `libxml-dev` now to work (because `bblfsh` client python needs it)
=> python: parse_uast_node should return Python instance

src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala
Fixes #348 
There are a couple changes here:
- If the repository is a siva repository, we don't cleanup the repo directory but it's parent, because siva repositories are created inside another directory, that way, when everything is deleted the only thing left is `processing-repositories` and `siva-files`.
- Adds cleanup to the `TaskContext` on completion and on failure. If for any reason the close did not get called, one of these handlers will cleanup the files. If the files have already been cleaned up, the listeners will do nothing.
With current 0.5.7 I managed to get a few repositories not cleaned up when executing it in standalone mode. I don't know exactly why, because I could not reproduce with custom jar for debugging, but with this for sure won't happen (at least I hope it …
=> provider: make sure all files are cleaned up

src/main/scala/tech/sourced/engine/exception/RepositoryException.scala, src/main/scala/tech/sourced/engine/iterator/BlobIterator.scala, src/main/scala/tech/sourced/engine/iterator/ChainableIterator.scala, src/main/scala/tech/sourced/engine/iterator/CleanupIterator.scala, src/main/scala/tech/sourced/engine/iterator/CommitIterator.scala, src/main/scala/tech/sourced/engine/iterator/GitTreeEntryIterator.scala
=> iterator: correctly handle git exceptions

DCO
=> Add DCO file

python/requirements.txt, python/setup.py
=> Fix pyspark version to 2.2.1

.travis.yml, Dockerfile, python/requirements.txt, python/setup.py
The image was not installing `requirements.txt` files, only data obtained from `setup.py` file. Removed `requirements.txt` file and manage all the python dependencies from `setup.py`. Doing this, the dependencies will be automatically resolved on install.
Fixes #405 
=> Install bblfsh on docker image.

Makefile
=> Fix bblfsh driver versions to avoid github connection problems.

README.md
=> docs: add python pre-requisites

Makefile
=> makefile: only add -dirty suffix when the repo is dirty

README.md
=> docs: state that this library reached EOL

.travis.yml, Dockerfile, Makefile, README.md, _examples/pyspark/pyspark-shell-basic.md, _examples/pyspark/pyspark-shell-classifying-languages.md, _examples/pyspark/pyspark-shell-lang-and-uast.md, _examples/pyspark/pyspark-shell-raw-repositories.md, _examples/pyspark/pyspark-shell-schemas.md, _examples/pyspark/pyspark-shell-uast-extraction.md, _examples/pyspark/pyspark-shell-xpath-query.md, _examples/scala/spark-shell-basic.md, _examples/scala/spark-shell-classifying-languages.md, _examples/scala/spark-shell-lang-and-uast.md, _examples/scala/spark-shell-raw-repositories.md, _examples/scala/spark-shell-schemas.md, _examples/scala/spark-shell-uast-extraction.md, _examples/scala/spark-shell-xpath-query.md, build.sbt, documentation/proposals/ENIP-000.md, python/Makefile, python/setup.py, src/main/scala/tech/sourced/engine/Engine.scala, src/test/scala/tech/sourced/engine/DefaultSourceSpec.scala
=> Rename project to jgit-spark-connector

src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala
- fix: incorrect destination path for files while copying
- fix: don't delete copied files after jgit repo instance created. It
still needs files to work with and we do cleaning afterwards in cleanupRepo
- improvement: copy only .git directory
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> fix support for remote standard repositories
